gourmet_homepage:
    path:     /
    defaults: { _controller: GourmetBundle:Main:index }

gourmet_loginpage:
    path:     /login
    defaults: { _controller: GourmetBundle:Main:login}

gourmet_chef_inscription_page:
    path:     /inscription_chef
    defaults: { _controller: GourmetBundle:Chef:chefInscription}

gourmet_chef_inscription_create:
    path:     /Create-chef
    defaults: { _controller: GourmetBundle:Chef:create }

gourmet_gourmet_inscription_page:
    path:     /inscription_gourmet
    defaults: { _controller: GourmetBundle:Gourmet:gourmetInscription}

gourmet_gourmet_inscription_create:
    path:     /Create
    defaults: { _controller: GourmetBundle:Gourmet:create }

gourmet_platpage:
    path:     /{id}/plat
    defaults: { _controller: GourmetBundle:Plat:index}
    requirements:
              id : \d+

gourmet_selection_platpage:
    path:     /selection_plat
    defaults: { _controller: GourmetBundle:Plat:selection}

gourmet_contactpage:
    path:     /contact
    defaults: { _controller: GourmetBundle:Main:contact}

gourmet_feedbackpage:
    path:     /feedback
    defaults: { _controller: GourmetBundle:Main:feedback}

gourmet_error404:
    path:     /error404
    defaults: { _controller: GourmetBundle:Main:error404}

gourmet_chefpage:
    path:     /{id}/chef
    defaults: { _controller: GourmetBundle:Chef:index}
    requirements:
              id : \d+

gourmet_cgu:
    path:     /cgu
    defaults: { _controller: GourmetBundle:Main:cgu}

gourmet_aide:
    path:     /aide
    defaults: { _controller: GourmetBundle:Main:aide}

gourmet_charte:
    path:     /charte
    defaults: { _controller: GourmetBundle:Main:charte}

gourmet_ccm:
    path:     /ccm
    defaults: { _controller: GourmetBundle:Main:ccm}

gourmet_confiance:
    path:     /confiance
    defaults: { _controller: GourmetBundle:Main:confiance}

gourmet_questions:
    path:     /questions
    defaults: { _controller: GourmetBundle:Main:questions}

gourmet_detail:
    resource: "@GourmetBundle/Resources/config/routing/gourmet.yml"
    prefix:   /gourmet
gourmet_message:
    resource: "@GourmetBundle/Resources/config/routing/message.yml"
    prefix:   /gourmet/message
gourmet_panier:
    resource: "@GourmetBundle/Resources/config/routing/panier.yml"
    prefix:   /gourmet/panier

gourmet_payment_resource:
    resource: "@GourmetBundle/Resources/config/routing/payment.yml"
    prefix:   /paiement

