gourmet_homepage:
    path:     /
    defaults: { _controller: GourmetBundle:Main:index }

gourmet_loginpage:
    path:     /login
    defaults: { _controller: GourmetBundle:Main:login}

gourmet_chef_inscription_page:
    path:     /inscription_chef
    defaults: { _controller: GourmetBundle:Chef:chefInscription}

gourmet_chef_inscription_create:
    path:     /Create
    defaults: { _controller: GourmetBundle:Chef:create }
gourmet_gourmet_inscription_page:
    path:     /inscription_gourmet
    defaults: { _controller: GourmetBundle:Gourmet:gourmetInscription}

gourmet_gourmet_inscription_create:
    path:     /Create
    defaults: { _controller: GourmetBundle:Gourmet:create }

gourmet_platpage:
    path:     /plat
    defaults: { _controller: GourmetBundle:Plat:index}

gourmet_selection_platpage:
    path:     /selection_plat
    defaults: { _controller: GourmetBundle:Plat:selection}

gourmet_contactpage:
    path:     /contact
    defaults: { _controller: GourmetBundle:Main:contact}

gourmet_feedbackpage:
    path:     /feedback
    defaults: { _controller: GourmetBundle:Main:feedback}

gourmet_detail:
    resource: "@GourmetBundle/Resources/config/routing/gourmet.yml"
    prefix:   /gourmet