back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /back/

chef:
    resource: "@ChefBundle/Resources/config/routing.yml"
    prefix:   /chef/

gourmet:
    resource: "@GourmetBundle/Resources/config/routing.yml"
    prefix:   /