avekapeti_back:
    resource: "@AvekApetiBackBundle/Resources/config/routing.yml"
    prefix:   /Admin

chef:
    resource: "@ChefBundle/Resources/config/routing.yml"
    prefix:   /chef/

gourmet:
    resource: "@GourmetBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: GourmetBundle:Main:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout