
security:
    always_authenticate_before_granting: true
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        AvekApeti\BackBundle\Entity\Utilisateur:
         # algorithm: sha512
          algorithm: bcrypt
          cost:      15
    role_hierarchy:
        # Un admin hérite des droits d'auteur et de modérateur
        ROLE_CHEF:       [ROLE_GOURMET]
        ROLE_ADMIN:       [ROLE_GOURMET, ROLE_CHEF]
        # On garde ce rôle superadmin, il nous resservira par la suite
        ROLE_SUPER_ADMIN: [ROLE_GOURMET, ROLE_CHEF, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      main:
        entity:
          class: AvekApetiBackBundle:Utilisateur
          property: email
      mix:
        chain:
          provider: [main]
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
                csrf_provider: security.csrf.token_manager
            logout:
                path:   logout
                target: /
            remember_me:
              key:      "%secret%"
              lifetime: 172800 # 2jours a définir en secondes
    access_control:
    - { path: ^/Admin, role: ROLE_ADMIN }
    - { path: ^/chef, role: ROLE_CHEF }
    - { path: ^/gourmet, role: ROLE_GOURMET }