<?php

namespace AvekApeti\BackBundle\Repository;

/**
 * CampagneionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampagneRepository extends \Doctrine\ORM\EntityRepository
{
}
