<?php

namespace AvekApeti\BackBundle\Repository;

/**
 * CommandePlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandePlatRepository extends \Doctrine\ORM\EntityRepository
{
}
