<?php

namespace AvekApeti\BackBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{

    public function getOneByED($User_id,$id)
    {

        $query = $this->_em->createQueryBuilder($User_id,$id)
            ->select("m")
            ->from("AvekApetiBackBundle:Message", "m")
            ->where('m.id = :id AND m.emetteur_user = :User_id')
            ->setParameter('User_id',$User_id)
            ->setParameter('id',$id)
            ->getQuery();
   //     die(dump($query));
        if($query->getSingleResult() == null)
        {
            $query = $this->_em->createQueryBuilder($User_id,$id)
                ->select("m")
                ->from("AvekApetiBackBundle:Message", "m")
                ->where('m.id = :id AND m.dest_user = :User_id')
                ->setParameter('User_id',$User_id)
                ->setParameter('id',$id)
                ->getQuery();
        }
        return $query->getSingleResult();
    }

    public function getByEmetteur($User_id)
    {

        $query = $this->_em->createQueryBuilder($User_id)
            ->select("m")
            ->from("AvekApetiBackBundle:Message", "m")
            ->where('m.emetteur_user = :User_id')
            ->setParameter('User_id',$User_id)
            ->getQuery();

        return $query->getResult();
    }
    public function getByDest($User_id)
    {

        $query = $this->_em->createQueryBuilder($User_id)
            ->select("m")
            ->from("AvekApetiBackBundle:Message", "m")
            ->where('m.dest_user = :User_id')
            ->setParameter('User_id',$User_id)
            ->getQuery();

        return $query->getResult();
    }
}
