<?php

namespace AvekApeti\BackBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\Mapping as ORM;


class PlatRepository extends \Doctrine\ORM\EntityRepository
{

    public function findOneIfChef($User_id,$id)
    {

        $query = $this->_em->createQueryBuilder($User_id,$id)
            ->select("p")
            ->from("AvekApetiBackBundle:Plat", "p")
            ->where('p.id = :id AND p.Utilisateur = :User_id')
            ->setParameter('User_id',$User_id)
            ->setParameter('id',$id)
            ->getQuery();

        return $query->getSingleResult();
    }

    public function findIfChef($User_id)
    {

        $query = $this->_em->createQueryBuilder($User_id)
            ->select("p")
            ->from("AvekApetiBackBundle:Plat", "p")
            ->where('p.Utilisateur = :User_id')
            ->setParameter('User_id',$User_id)
            ->getQuery();

        return $query->getResult();
    }
}
