<?php

namespace AvekApeti\BackBundle\Repository;

/**
 * TypeLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
