avek_apeti_back_typecommande:
    resource: "@AvekApetiBackBundle/Resources/config/routing/typecommande.yml"
    prefix:   /typecommande

avek_apeti_back_mail:
    resource: "@AvekApetiBackBundle/Resources/config/routing/mail.yml"
    prefix:   /mail

avek_apeti_back_typelivraison:
    resource: "@AvekApetiBackBundle/Resources/config/routing/typelivraison.yml"
    prefix:   /typelivraison

avek_apeti_back_specialite:
    resource: "@AvekApetiBackBundle/Resources/config/routing/specialite.yml"
    prefix:   /specialite

avek_apeti_back_plat:
    resource: "@AvekApetiBackBundle/Resources/config/routing/plat.yml"
    prefix:   /plat

avek_apeti_back_message:
    resource: "@AvekApetiBackBundle/Resources/config/routing/message.yml"
    prefix:   /message

avek_apeti_back_menu:
    resource: "@AvekApetiBackBundle/Resources/config/routing/menu.yml"
    prefix:   /menu

avek_apeti_back_facturation:
    resource: "@AvekApetiBackBundle/Resources/config/routing/facturation.yml"
    prefix:   /facturation

avek_apeti_back_commande:
    resource: "@AvekApetiBackBundle/Resources/config/routing/commande.yml"
    prefix:   /commande

avek_apeti_back_categorie:
    resource: "@AvekApetiBackBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie

avek_apeti_back_campagne:
    resource: "@AvekApetiBackBundle/Resources/config/routing/campagne.yml"
    prefix:   /campagne

avek_apeti_back_avis:
    resource: "@AvekApetiBackBundle/Resources/config/routing/avis.yml"
    prefix:   /avis

avekapeti_back_chef:
    resource: "@AvekApetiBackBundle/Resources/config/routing/chef.yml"
    prefix:   /chef

avekapeti_back_utilisateur:
    resource: "@AvekApetiBackBundle/Resources/config/routing/utilisateur.yml"
    prefix:   /utilisateur


avekapeti_back_image:
    resource: "@AvekApetiBackBundle/Resources/config/routing/image.yml"
    prefix:   /image

avekapeti_back_groupe:
    resource: "@AvekApetiBackBundle/Resources/config/routing/groupe.yml"
    prefix:   /groupe


index:
    path:     /
    defaults: { _controller: AvekApetiBackBundle:Main:index }
