panier_index:
    path:     /
    defaults: { _controller: "GourmetBundle:Panier:index" }
panier_plat_ajout:
    path:     /ajout/plat/{idPlat}
    defaults: { _controller: "GourmetBundle:Panier:ajoutPlatPanier" }

panier_plat_suppr:
    path:     /suppr/plat/{idPlat}
    defaults: { _controller: "GourmetBundle:Panier:suppPlatPanier" }

panier_reset:
    path:     /reset
    defaults: { _controller: "GourmetBundle:Panier:resetPanier" }

panier_menu_ajout:
    path:     /ajout/menu/{idMenu}
    defaults: { _controller: "GourmetBundle:Panier:ajoutMenuPanier" }

panier_menu_suppr:
    path:     /suppr/menu/{idMenu}
    defaults: { _controller: "GourmetBundle:Panier:suppMenuPanier" }
panier_widget_panier:
    path:     /widget
    defaults: { _controller: "GourmetBundle:Panier:widgetPanier" }

