chef_profil:
    path:     /profil
    defaults: { _controller: "ChefBundle:Chef:profil" }
chef_update:
    path:     /update
    defaults: { _controller: "ChefBundle:Chef:update" }
    methods:  [POST, PUT]