chef_profil:
    path:     /profil
    defaults: { _controller: "ChefBundle:Chef:profil" }
chef_chef_update:
    path:     /update
    defaults: { _controller: "ChefBundle:Chef:update" }
    methods:  [POST, PUT]
chef_plat:
    resource: "@ChefBundle/Resources/config/routing/plat.yml"
    prefix:   /plat
chef_commande:
    path:     /commande
    defaults: { _controller: "ChefBundle:Commande:index" }
chef_commande_details:
    path:     /commande/{id}/show
    defaults: { _controller: "ChefBundle:Commande:show" }
chef_profil_public:
    path:     /profil-public
    defaults: { _controller: "ChefBundle:Chef:profilpublic" }
