categorie:
    path:     /
    defaults: { _controller: "AvekApetiBackBundle:Categorie:index" }

categorie_show:
    path:     /{id}/show
    defaults: { _controller: "AvekApetiBackBundle:Categorie:show" }

categorie_new:
    path:     /new
    defaults: { _controller: "AvekApetiBackBundle:Categorie:new" }

categorie_create:
    path:     /create
    defaults: { _controller: "AvekApetiBackBundle:Categorie:create" }
    methods:  POST

categorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "AvekApetiBackBundle:Categorie:edit" }

categorie_update:
    path:     /{id}/update
    defaults: { _controller: "AvekApetiBackBundle:Categorie:update" }
    methods:  [POST, PUT]

categorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "AvekApetiBackBundle:Categorie:delete" }
    methods:  [POST, DELETE]
