plat:
    path:     /
    defaults: { _controller: "AvekApetiBackBundle:Plat:index" }

plat_show:
    path:     /{id}/show
    defaults: { _controller: "AvekApetiBackBundle:Plat:show" }

plat_new:
    path:     /new
    defaults: { _controller: "AvekApetiBackBundle:Plat:new" }

plat_create:
    path:     /create
    defaults: { _controller: "AvekApetiBackBundle:Plat:create" }
    methods:  POST

plat_edit:
    path:     /{id}/edit
    defaults: { _controller: "AvekApetiBackBundle:Plat:edit" }

plat_update:
    path:     /{id}/update
    defaults: { _controller: "AvekApetiBackBundle:Plat:update" }
    methods:  [POST, PUT]

plat_delete:
    path:     /{id}/delete
    defaults: { _controller: "AvekApetiBackBundle:Plat:delete" }
    methods:  [POST, DELETE]
